version: '2'
services:
  redis:
    image: redis
  web:
    build: .
    command: bundle exec rackup -o 0.0.0.0 -p 9000
    volumes:
      - .:/drone
    ports:
      - "9000:9000"
    depends_on:
      - redis
    environment:
      - DRONE_ENV=development
      - DRONE_OAUTH_CLIENT_ID=abc
      - DRONE_OAUTH_CLIENT_SECRET=123
      - DRONE_OAUTH_HOST=http://localhost:7000/
      - DRONE_OAUTH_REDIRECT_URI=http://localhost:9000/services/drone/oauth/receive/default
      - DRONE_WEB_USERNAME=drone
      - DRONE_WEB_PASSWORD=drone
      - DRONE_WEB_PREFIX=/services/drone
      - DRONE_REDIS_HOST=redis
      - DRONE_REDIS_PORT=6379
#  render:
#    build: .
#    command: bundle exec bin/drone work
#    volumes:
#      - .:/drone
#    depends_on:
#      - redis
#    environment:
#      - DRONE_ENV=development
#      - DRONE_REDIS_HOST=redis
#      - DRONE_REDIS_PORT=6379
