defaults: &defaults

  # Number of targets to pop off the pending queue per batch
  cycle_count: 1

  # Minimum amount of time between captures (in seconds)
  min_capture_interval: 3600

  # Run PhantomJS in debug mode?
  phantomjs_debug_mode: false

  # Ignore invalid SSL certificates
  phantomjs_ignore_ssl_errors: true

  # Recipes that should be executed on an ongoing basis for
  # each Target URL in the DB.
  #
  # Important: 'thumbnail' is a mandatory recipe; you can modify the definition,
  # but it should not be removed.
  recipes:
    thumbnail:
      format: png
      output_height: 256
      output_width: 256
      viewport_height: 1100,
      viewport_width: 650,

  # Number of threads that generate screen captures (or blank for no multithreading)
  thread_count: 

  # Prefix under which to serve Drone's web interface
  prefix:

development:
  <<: *defaults
  prefix: 'services/drone'
  credentials:
    dasheroo:
      scheme: oauth2
      oauth_client_id: b3bf79611b812e9f95a486ab272ac8858335bbfd91500bee273e0953e4f191df
      oauth_client_secret: 7a1010c9fdfe00ce668d44e9348d2c949b0e5dbf83518d89296417fac043c829
      oauth_host: http://localhost:7000/
      oauth_redirect_uri: http://localhost:9000/oauth/receive/dasheroo

test:
  <<: *defaults
  credentials:
    dasheroo:
      scheme: oauth2
      oauth_client_id: b3bf79611b812e9f95a486ab272ac8858335bbfd91500bee273e0953e4f191df
      oauth_client_secret: 7a1010c9fdfe00ce668d44e9348d2c949b0e5dbf83518d89296417fac043c829
      oauth_host: http://localhost:7000/
      oauth_redirect_uri: http://localhost:9000/oauth/receive/dasheroo

prodlike: &prodlike
  <<: *defaults
  phantomjs_path: /usr/bin/phantomjs
  imagemagick_identify_path: /usr/bin/identify
  imagemagick_convert_path: /usr/bin/convert

integrations:
  <<: *prodlike
  credentials:
    dasheroo:
      scheme: oauth2
      oauth_client_id: b3bf79611b812e9f95a486ab272ac8858335bbfd91500bee273e0953e4f191df
      oauth_client_secret: 7a1010c9fdfe00ce668d44e9348d2c949b0e5dbf83518d89296417fac043c829
      oauth_host: https://integrations-staging.dasheroo.com/
      oauth_redirect_uri: https://integrations-staging.dasheroo.com/services/drone/oauth/receive/dasheroo

staging:
  <<: *prodlike
  credentials:
    dasheroo:
      scheme: oauth2
      oauth_client_id: b3bf79611b812e9f95a486ab272ac8858335bbfd91500bee273e0953e4f191df
      oauth_client_secret: 7a1010c9fdfe00ce668d44e9348d2c949b0e5dbf83518d89296417fac043c829
      oauth_host: https://staging.dasheroo.com/
      oauth_redirect_uri: https://staging.dasheroo.com/services/drone/oauth/receive/dasheroo

production:
  <<: *prodlike
  credentials:
    dasheroo:
      scheme: oauth2
      oauth_client_id: b3bf79611b812e9f95a486ab272ac8858335bbfd91500bee273e0953e4f191df
      oauth_client_secret: 7a1010c9fdfe00ce668d44e9348d2c949b0e5dbf83518d89296417fac043c829
      oauth_host: https://www.dasheroo.com/
      oauth_redirect_uri: https://www.dasheroo.com/services/drone/oauth/receive/dasheroo
